on: [push, pull_request]
name: Run Plank Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21"]  # Add more Golang versions if needed
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache Build Dependencies  # Speeds up subsquent builds
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**/go.sum') }}
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Test Plank
      run: go test -v -race -covermode atomic -coverprofile=profile.cov ./... 
    - name: Send Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
